# Generated by Django 5.1.4 on 2024-12-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_name_alter_document_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
